package com.exam;
// Generated Apr 27, 2019 11:39:42 AM by Hibernate Tools 4.3.1

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Student generated by hbm2java
 */
@Entity
@XmlRootElement

public class Student implements java.io.Serializable {

    @Id
    @GeneratedValue
    private int id;
    private String name;
    private String email;

    public Student() {
    }

    public Student(int id) {
        this.id = id;
    }

    public Student(int id, String name, String email) {
        this.id = id;
        this.name = name;
        this.email = email;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

}
